### ISSUE TITLE
Does not support Chinese!

### ISSUE THREAD

**Issue by gMan1990** [jroyals/log4j-properties-converter#7]
properties like this:
log4j.appender.SecureAppender.partialEncryptKeys=\u5361\u53F7
log4j.appender.SecureAppender.partialEncryptKeys=卡号

**Comment by jroyals** [comment]
I've updated the web app version and I think that works now, let me know how you go. http://log4j-props2xml.appspot.com/#. I'll update the CLI version in the next day or so.
